### PR TITLE
Add support for progamatically flipping cards

### LINKED ISSUE #5: Add support for progamatically flipping the card.
There are use cases where the flip state should be changed programatically (data-binding or JS). 
Currently the card automatically flips as soon as the user moves the mouse over it.

### PR DESCRIPTION
**Pull request by timeu**
A nohover attribute was added in order to disable the automatic flippin of cards on hover.
Furthermore a JS API (toggle, showBack, etc) was added a flipped property that allows to change the flip state via data-binding or imperatively.

A flipend event will be fired as soon as the transition ends. Furthermre the flip-card will listen for a show event that is fired from child elements and reveal the corresponding side.

The external stylesheet was moved into the html template as external stylesheets have been deprecated.
This fixes #5

### CODE REVIEW

**Comment by rupl** [comment]
hey thanks! this looks great when I skim the diff. I'm running an art installation at a festival this week, but when I return I will give this a full test and merge the work.

**Comment by timeu** [comment]
@rupl: If you want to check it out, you can checkout my forked repo and then just run polyserve in it. 
I updated the demo page to showcase the new features. 

Some additional notes. 
I moved the styles from the external CSS into the dom template bcasause external CSS have been deprecated. Also I removed the default styling (background, border, etc) from those styles. IMHO those styles should be done by the user of the flip-card (by default there should be no styling at all). We could define a mixin that is applied for `front`  and `back`  but styling is quite easy (check out the demo.html). 

The added functionality is quite similar to [xtags flipbox](https://github.com/x-tag/flipbox)

**Comment by rupl** [comment]
Hey man you want commit access on this thing? I was skimming the other PRs and realize you've written more code than I have at this point 😁

**Comment by timeu** [comment]
@rupl: Sure, I am fine with being contributor.

**Comment by timeu** [comment]
@rupl Great thanks, so I would go ahead and merge this pull rqeuest and then bump/release a new version of the flip-card, if that's ok with you

**Comment by rupl** [comment]
absolutely, thanks for keeping this thing fresh! 👍

**Comment by timeu** [comment]
Ok updated the README.md, pushed the new demo page, bumped the version (1.0.0 -> 1.1.0) and drafted a new release. Hope this is fine.

**Comment by rupl** [comment]
🙏

**Pull request merged**
